### ISSUE TITLE
QuicrClient: Support Message Handling for MoQ Mesages

### ISSUE THREAD

**Issue by suhasHere** [Quicr/libquicr#137]
This work requires few changes
1: Mapping between MOQ identifiers ( track-alias, subscribe-id, full trackname) to QUICR identifiers ( Namespace, Name)
2. Support handlers for MoQ Messages
3. Handle subscriptions ( for publishers) forwarded
4. URI convertor integration

**Comment by TimEvens** [comment]
I believe this is covered by #136  and #161
