### ISSUE TITLE
Map design between MoQ identifiers and QuicR identifers

### ISSUE THREAD

**Issue by suhasHere** [Quicr/libquicr#143]
MoQ uses slightly different naming schemes that can be 1:1 mapped to QuicR names. 
We need to agree on it before making actual changes.

Some initial thoughts are here, but need not be the only way
: https://github.com/Quicr/libquicr/blob/moq-suhas-feb2024/src/quicr_client_raw_session.cpp

**Comment by GhostofCookie** [comment]
Is this still relevant after the big refactor?

**Comment by GhostofCookie** [comment]
Closing due to staleness. If this is an error, then we can reopen.
