### ISSUE TITLE
question about make cert 

### ISSUE THREAD

**Issue by linsheng1** [Quicr/libquicr#333]
Hello, there is an issue with the command line `make cert`. I am using a Mac, and the details of the problem are as follows. Could you please assist me with this issue? Thank you.

```
(base) % make 
[  0%] Built target boringssl_prefix_symbols
[ 18%] Built target fipsmodule
[ 70%] Built target crypto
[ 78%] Built target ssl
[ 81%] Built target decrepit
[ 82%] Built target picotls-core
[ 82%] Built target picotls-openssl
[ 88%] Built target picotls-minicrypto
[ 96%] Built target picoquic-core
[ 97%] Built target picoquic-log
[ 98%] Built target spdlog
[100%] Built target quicr
[100%] Built target qclient
[100%] Built target qserver
(base) % make cert
make: *** No rule to make target `cert'.  Stop.
(base) % pwd
/Users/mac/Code/c/libquicr/libquicr/cmd/examples
```

**Comment by RichLogan** [comment]
@linsheng1 try running `make cert` from the root of the libquicr repo rather than `/cmd/examples/.

**Comment by linsheng1** [comment]
Thank you for your response, but it seems there are still some issues.
```
(base)  libquicr % make cert
make: *** No rule to make target `cert'.  Stop.
(base)  libquicr % pwd
/Users/mac/Code/c/libquicr/libquicr
(base)  libquicr % cd ..
(base)  libquicr % make cert
make: *** No rule to make target `cert'.  Stop.
(base)  libquicr % pwd
/Users/mac/Code/c/libquicr
```

**Comment by RichLogan** [comment]
I'm a bit confused by your double libquicr/libquicr folder structure. I've uploaded myself generating a build and certificate from scratch here if that's any clearer: https://asciinema.org/a/V8PgbN2dFRGrVxPZ5uT1Djs2r

You can also just run the command that's in the Makefile itself if that's easier:

```
openssl req -nodes -x509 -newkey rsa:2048 -days 365 \
        -subj "/C=US/ST=CA/L=San Jose/O=Cisco/CN=test.m10x.org" \
        -keyout <your_build_directory>/cmd/examples/server-key.pem -out <your_build_directory>/cmd/examples/server-cert.pem
```

**Comment by RichLogan** [comment]
@linsheng1 Oh, I've think I've just realized what it is. Have you done an in-source generation of the CMake build? That will overwrite our Makefile with the generated Makefile of the build, which that won't have our custom targets in (like `cert`). If that's the case, I would advise against ever doing in-source builds with CMake, they will pollute the source tree with build artifacts. For what it's worth, the CMake docs make the same reccomendation: https://cmake.org/cmake/help/book/mastering-cmake/chapter/Getting%20Started.html#directory-structure

**Comment by linsheng1** [comment]
This is the problem I encountered, and it has been resolved using the method you suggested. Thank you!
